### ISSUE TITLE
There is an error in the description of zabbix in schema.yaml

### ISSUE THREAD

**Issue by nsano-rururu** [JasperJuergensen/elastalert#10]
schema.yaml

**current**

```yaml
  ### Zabbix
  zbx_sender_host: {type: string}
  zbx_sender_port: {type: integer}
  zbx_host: {type: string}
  zbx_item: {type: string}
```

**after**

zbx_item → zbx_key

```yaml
  ### Zabbix
  zbx_sender_host: {type: string}
  zbx_sender_port: {type: integer}
  zbx_host: {type: string}
  zbx_key: {type: string}
```
